### ISSUE TITLE
Add a way to remove signature

### ISSUE THREAD

**Issue by mlocati** [ebourg/jsign#1]
First of all... Thanks for this great tool!

This isn' an issue, but it would be nice to have a way to remove signature from already signed files. This way we could for instance un-sign, edit the file (eg by adding some data to an sfx exe) and re-sign it...

Thank you again

**Comment by ebourg** [comment]
@mlocati What tool did you use to create the SFX exe?

**Comment by mlocati** [comment]
> @mlocati What tool did you use to create the SFX exe?

Here's the relevant part of my project:

1) I already have a signed SFX exe

2) I add to the sfx some new files via PHP with [PclZip](http://www.phpconcept.net/pclzip/pclzip-downloads) (it keeps the sfx executable):  
```php
$pclZip = new PclZip($existingSfx);
$pclZip->add($newFiles,  PCLZIP_OPT_REMOVE_ALL_PATH);
```

3) I re-sign the sfx with `jsign`

**Comment by ebourg** [comment]
@mlocati I added a `replace` parameter to overwrite a previous signature with a new one. Let me know how it works for you.
