### ISSUE TITLE
-bash: /usr/bin/jsign: /bin/sh^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by MrAlex94** [ebourg/jsign#101]
Great tool - thank you for all the hard work!

Not sure if this is platform specific, but installing jsign via `sudo apt install ./jsign_4.0_all.deb` and then trying to run via `jsign` results in `-bash: /usr/bin/jsign: /bin/sh^M: bad interpreter: No such file or directory`.

There's an easy remedy: `sed -i -e 's/\r$//' /usr/bin/jsign`

Not sure if something is happening at the packaging stage or the way it's installed.

**Comment by ebourg** [comment]
Thank you for the report, that's a packaging issue. I'll get that fixed.

**Comment by ebourg** [comment]
The jsign_4.0_all.deb file is now fixed.

**Comment by rhartman93** [comment]
Confirming that I ran into the same when installing the rpm from: https://ebourg.github.io/jsign/ vesrion 4.0-1.

**Comment by rhartman93** [comment]
I should have a chance in the next week or so to give this a shot, will report back
