### ISSUE TITLE
Invalid signature after re-signing

### ISSUE THREAD

**Issue by netmackan** [ebourg/jsign#11]
I'm trying jsign (v1.2) to sign a binary which seems to work fine however, Windows complains on the signature and running signtool verify gives an error message (see below output).

Using the signtool I am able to sign the same binary and verify then gives no error so I suspect the issue is with jsign (or my usage of it).

Any ideas?

Best regards,
Markus

---

```
signtool.exe verify /pa /v c:\temp\pidgin-signed-7.exe

Verifying: c:\temp\pidgin-signed-7.exe
Hash of file (sha1): E3B61AFB75FC8E7132ADF407A598B5116B00E249

Signing Certificate Chain:
    Issued to: DSS Root CA 10
    Issued by: DSS Root CA 10
    Expires:   Tue May 27 09:14:27 2036
    SHA1 hash: 5BBB15488C0ED21579ACE90B47E0C701F0EE51C1

    Issued to: AuthCode Signer 1
    Issued by: DSS Root CA 10
    Expires:   Sun Mar 03 10:39:10 2030
    SHA1 hash: 7837BC0F2B0DE7CACCD73872C66CD238D23DF7AA

The signature is timestamped: Tue Mar 03 13:25:25 2015
Timestamp Verified by:
    Issued to: UTN-USERFirst-Object
    Issued by: UTN-USERFirst-Object
    Expires:   Tue Jul 09 19:40:36 2019
    SHA1 hash: E12DFB4B41D7D9C32B30514BAC1D81D8385E2D46

    Issued to: COMODO Time Stamping Signer
    Issued by: UTN-USERFirst-Object
    Expires:   Mon May 11 00:59:59 2015
    SHA1 hash: 3DBB6DB5085C6DD5A1CA7F9CF84ECB1A3910CAC8

Number of files successfully Verified: 0
Number of warnings: 0
Number of errors: 1
SignTool Error: WinVerifyTrust returned error: 0x80096010
    Det gick inte att verifiera objektens digitala signatur.
```

---

(The last line translated is something like "Not possible to verify the objects digital signature")

**Comment by ebourg** [comment]
Do you get the same error if the file is signed but not timestamped?

**Comment by netmackan** [comment]
I haven't tried without timestamping yet. Will try that now.

However, I did try some other files now which worked well. One difference I noticed was that the file that fails to verify (pidgin.exe) already had a signature from the creator.

For reference I have uploaded all files here both original and signed versions as well as the test keystore:
http://wwwpriv.primekey.se/~markus/jsign-11/

**Comment by netmackan** [comment]
I got the same error also without timestamping:

    signtool.exe verify /pa /v c:\temp\pidgin-signed-9-notsa.exe
	Verifying: c:\temp\pidgin-signed-9-notsa.exe
	Hash of file (sha1): 084BDD66547B6520F119EFBAF4B6AFCBDB436C33

	Signing Certificate Chain:
	    Issued to: DSS Root CA 10
	    Issued by: DSS Root CA 10
	    Expires:   Tue May 27 09:14:27 2036
	    SHA1 hash: 5BBB15488C0ED21579ACE90B47E0C701F0EE51C1

		Issued to: AuthCode Signer 1
		Issued by: DSS Root CA 10
		Expires:   Sun Mar 03 10:39:10 2030
		SHA1 hash: 7837BC0F2B0DE7CACCD73872C66CD238D23DF7AA

	File is not timestamped.


	Number of files successfully Verified: 0
	Number of warnings: 0
	Number of errors: 1
	SignTool Error: WinVerifyTrust returned error: 0x80096010
		Det gick inte att verifiera objektens digitala signatur.
---

**Comment by netmackan** [comment]
I tried signing a file that was already signed and got the error again, so it seems to be an issue with re-signing already signed files:

    signtool.exe verify /pa /v c:\temp\svnsync-signed-1-signed-2.exe

	Hash of file (sha1): 037996EB978834E5C555254C64D8A42B51D1996B

	Signing Certificate Chain:
	    Issued to: DSS Root CA 10
	    Issued by: DSS Root CA 10
	    Expires:   Tue May 27 09:14:27 2036
	    SHA1 hash: 5BBB15488C0ED21579ACE90B47E0C701F0EE51C1

		Issued to: AuthCode Signer 1
		Issued by: DSS Root CA 10
		Expires:   Sun Mar 03 10:39:10 2030
		SHA1 hash: 7837BC0F2B0DE7CACCD73872C66CD238D23DF7AA

	The signature is timestamped: Tue Mar 03 15:41:47 2015
	Timestamp Verified by:
	    Issued to: UTN-USERFirst-Object
	    Issued by: UTN-USERFirst-Object
	    Expires:   Tue Jul 09 19:40:36 2019
	    SHA1 hash: E12DFB4B41D7D9C32B30514BAC1D81D8385E2D46

		Issued to: COMODO Time Stamping Signer
		Issued by: UTN-USERFirst-Object
		Expires:   Mon May 11 00:59:59 2015
		SHA1 hash: 3DBB6DB5085C6DD5A1CA7F9CF84ECB1A3910CAC8


	Number of files successfully Verified: 0
	Number of warnings: 0
	Number of errors: 1
	SignTool Error: WinVerifyTrust returned error: 0x80096010
		Det gick inte att verifiera objektens digitala signatur.
----

**Comment by ebourg** [comment]
I think I understand what happens when re-signing:
1. jsign computes the digest of the file and skips the existing certificate table in the process
2. jsign writes the new certificate table at the end of the file and dereferences the previous one from the data directory table.
3. the old certificate table is still in the file, re-computing the digest now takes it into account. This gives a digest different from the one used for the new signature which is now invalid.

This issue can be addressed by dereferencing the old certificate table before creating the new signature. This would work when replacing the current signature with a new one, but not when adding a signature to the current one. This is sub-optimal though since it always increases the size of the file. When the certificate table is at the end of the file jsign should simply overwrite it. This will also work when appending an additional signature.
