### ISSUE TITLE
Github release for jsign 4.1

### ISSUE THREAD

**Issue by zhovner** [ebourg/jsign#113]
Thank you for the great tool! 
Jsign version 4.1 works like a charm with Yubikey from ssl.com 

But it's quite difficult to build it using `mvn`, so please make a github release of 4.1 version.

**Comment by bse-sja** [comment]
I 2nd the request for a  github release of 4.1 version.
Alternately are there build instructions or a docker container ?

**Comment by bse-sja** [comment]
Turns out by using maven docker image, the build is easy:

git clone https://github.com/ebourg/jsign.git
cd jsign
docker run -it --rm --name my-maven-project -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn clean install
