### ISSUE TITLE
NoClassDefFoundError with Bouncy Castle FIPS

### ISSUE THREAD

**Issue by RenQingWan** [ebourg/jsign#116]
I used jsign-core in my project,i also used bouncy castle fips version jar,my projec。
an exception occurred ：Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder.
I have found this class both in bcprove-jdk15on jar and bc-fips jar,they have the same name and location.What can i do?
Can I submit code that uses the fips version bouncy castle jar?

**Comment by ebourg** [comment]
What version of Bouncy Castle do you use?

**Comment by RenQingWan** [comment]
> 你用的是什么版本的充气城堡？

I used bcpkix-fips 1.0.5,and it has bc-fips 1.0.2.3
I used jsign-core 3.1,and it has bcprov-jdk15on 1.64

**Comment by ebourg** [comment]
Bouncy Castle FIPS seems to be binary incompatible with the standard version and jsign won't work with it. You can try depending on net.jsign:jsign instead of net.jsign:jsign-core, the all in one jar contains a shaded version of BC that will not conflict with the FIPS version.

**Comment by RenQingWan** [comment]
ok，i will have a try,thank you for your reply
