### ISSUE TITLE
corrupted signed executable

### ISSUE THREAD

**Issue by zosrothko** [ebourg/jsign#121]
Hi

With the jsign-4.0.jar, I am signing an executable produced by launch4j with a wrapped jar,  named '`EnterpriseStudio.exe`' . While the non signed executable is working well, the signed one seems to corrupt the executable. There is a pop-up windows as below

![image](https://user-images.githubusercontent.com/7262593/164262541-ce30f36d-52e2-4616-81b3-43e1333b2d83.png)

Here the EnterpriseStudio.exe as a zipped file
[EnterpriseStudio.zip](https://github.com/ebourg/jsign/files/8522786/EnterpriseStudio.zip)

**Comment by ebourg** [comment]
Yes this is a known issue (see #80). The workaround is to define the main class in the launch4j configuration:

    <classPath>
      <mainClass>org.acme.Main</mainClass>
    </classPath>
