### ISSUE TITLE
Unknown Pulisher on .EXE Signed By Jsign

### ISSUE THREAD

**Issue by Amin-Matola** [ebourg/jsign#127]
I Signed an EXE from .jks file using JSign as described at https://ebourg.github.io/jsign/
Under **Example using a Java keystore:** section.

The process went smooth, only that when I upload the .exe to the server and download, running it brings the same 
"Unknown Publisher" thing, just as before signing it, but viewing properties, it shows the Digital Signature is there.

- I wonder if I miss anything? 😕

**Comment by ebourg** [comment]
Is the signature valid in the digital signature tab?

**Comment by Amin-Matola** [comment]
Kindly, refer the attachment:

![sg](https://user-images.githubusercontent.com/31763634/171034301-b445e514-8f8d-4d8a-ba36-cbf0011e7998.PNG)

**Comment by Amin-Matola** [comment]
> Kindly, refer the attachment:
> 
> ![sg](https://user-images.githubusercontent.com/31763634/171034301-b445e514-8f8d-4d8a-ba36-cbf0011e7998.PNG)

**Comment by Amin-Matola** [comment]
> Is the signature valid in the digital signature tab?

Kindly, refer to the screen below:

![sg](https://user-images.githubusercontent.com/31763634/171034631-d1ce0a37-a60d-4db9-af78-d696e0214a83.PNG)

**Comment by ebourg** [comment]
And what is displayed if you open the details of the signature?

**Comment by Amin-Matola** [comment]
> And what is displayed if you open the details of the signature?

![sd1](https://user-images.githubusercontent.com/31763634/171163256-a9c6fb96-8bb5-454a-bf40-fe8bc4b530f7.PNG)

and then viewing details gives out this 👇 

![sd2](https://user-images.githubusercontent.com/31763634/171163352-4886ee65-fba0-4b93-be16-ab38e73e0dd1.PNG)

**Comment by ebourg** [comment]
Your certificate is self signed, this is not trusted by Windows. You have to get a certificate issued by a valid certification authority.

**Comment by Amin-Matola** [comment]
> Your certificate is self signed, this is not trusted by Windows. You have to get a certificate issued by a valid certification authority.

Alright, I get it... Thanks alot dude.
