### ISSUE TITLE
Catalog file signing

### ISSUE THREAD

**Issue by mikehearn** [ebourg/jsign#131]
Microsoft CAT files can be code signed. Does anyone know anything about this format and how hard it is to sign CAT files with jsign? There's some docs here:

https://blog.cryptomilk.org/2016/10/25/hack-ms-catalog-files-and-digital-signatures

**Comment by ebourg** [comment]
Thank you for the suggestion, I'm working on implementing it. Catalog files are very easy to sign, the file is simply a PKCS#7 SignedData structure with only the ContentInfo element.

**Comment by ebourg** [comment]
@mikehearn it's now implemented, please let me know how it work for you

**Comment by mikehearn** [comment]
Thank you! It might take a little while to test because right now the feature I'd need this for is low priority, but it's much appreciated and will prove useful soon enough.
