### ISSUE TITLE
jsign-maven-plugin: Allow referencing credentials from server settings in settings.xml

### ISSUE THREAD

**Issue by kwin** [ebourg/jsign#135]
It should be possible to reference credentials from the settings.xml (https://maven.apache.org/settings.html#Servers). That requires to reference just a server id in the plugin parameters.

**Comment by ebourg** [comment]
Do you mean the keystore credentials?

**Comment by ebourg** [comment]
Do you know of other Maven plugins doing this already?

**Comment by kwin** [comment]
This also requires have individual parameters for signing with a remote service instead of requiring concatenation in one parameter.

**Comment by ebourg** [comment]
maven-gpg-plugin uses an extra element for the serverId

https://github.com/apache/maven-gpg-plugin/blob/maven-gpg-plugin-3.0.1/src/main/java/org/apache/maven/plugins/gpg/AbstractGpgMojo.java#L213

I'm tempted to use a prefix instead, something like:

    <storepass>mvn:serverId</storepass>

That would be consistent with the other prefixes supported (`env:` and `file:`).

**Comment by ebourg** [comment]
I don't have the time to implement this right now, but if you send a PR I'll review and merge it.

**Comment by ebourg** [comment]
This is now implemented, please let me know how it works for you.
