### ISSUE TITLE
Failure to replace an extended signature

### ISSUE THREAD

**Issue by turalf** [ebourg/jsign#143]
When  `--replace` signing an `.msi` file that has an extended signature, the verification of the file fails. 
To reproduce:
1. Get the file signed with an extended signature (maybe `osslsigncode`?). Or use a file that already has an extended signature.
```bash
osslsigncode sign -h sha256 -pkcs12 <keyfile> -pass <password> -in <infile> -out <outfile>
```
3. Use `jsign` and `--replace` flag to remove the current signature and add fresh one. 
```bash 
jsign --replace <path to the file>
```
4. Verify (I used `signtool` in Windows). Verification fails. 
```bash
signtool verify /v /pa <path to the file>
```

Expected behavior: If `jsign` does not support extended signatures, probably it is better to reject the signing request even with `--replace` flag passed in. If that flag is not provided, `jsign` properly rejects with that message

`jsign: The file has an extended signature which isn't supported by Jsign, it can't be signed without replacing the existing signature`

However, if `jsign` is supposed to support replacing the extended signatures as well, I guess that is a legitimate bug.

**Comment by ebourg** [comment]
@turalf The extended signature is now better handled, you can add a signature without replacing it when there is an extended signature entry in the MSI file. Replacing the signature also works, but I've found some edge cases where the new signature is still invalid.
