### ISSUE TITLE
Sign arbitrary data file and produce detached PKCS#7 signature file?

### ISSUE THREAD

**Issue by wilx** [ebourg/jsign#146]
Is it possible to use this utility to sign arbitrary data file and produce PKCS#7 detached signature which would be verifiable via, e.g., [`signver`](https://manpages.ubuntu.com/manpages/jammy/man1/signver.1.html) utility?

**Comment by wilx** [comment]
Signing an entire file is what I want.

**Comment by ebourg** [comment]
Another point worth noting, the object signed by Authenticode is a SpcIndirectDataContent structure containing the hash of the file. Unless signver knows how to build this structure it won't be able to verify the signature.
