### ISSUE TITLE
AWS KMS with service-linked role

### ISSUE THREAD

**Issue by vmal-altium** [ebourg/jsign#147]
My requirement is to use the KMS option of jsign from an EC2 instance with an appropriate role, without having to manually specify credentials in the command line.

As a result, I was wondering whether there are specific reasons not to use the AWS SDK rather than API (aside from the extra dependency).  The SDK covers more options in terms of credentials (see [DefaultCredentialsProvider](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.html)), and hides the request-signing business.

I have done a prototype with the SDK, which seems to work, and I wanted to get your view on how to take this forward.

**Comment by ebourg** [comment]
I try to avoid the AWS SDK due to its size, the REST API is simple enough to be called directly.

How do you call the API with a service linked role? Can you get an access key and a secret key with the AWS CLI?

**Comment by ebourg** [comment]
The input variables are the endpoint (169.254.169.254 in this example) and the name of the role?

**Comment by vmal-altium** [comment]
169.254.169.254 is a fixed IP address that AWS uses to offer the [metadata service](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html) to all EC2 instances, so that is not going to change, and can be essentially hardcoded.

The role is assigned externally to the EC2 instance (AWS console or so), and defines the permissions it has to interact with AWS services (KMS here). The metadata service (IMDS) can be queried from within the instance to know the currently assigned role name, and from that, credentials to make requests to the other AWS services.

So there is no input variable in this case; credentials are available from the fact that the code is run from within an authorised EC2 instance. I would still offer the possibility to pass credentials through the command line (as now), but if not provided, then it would try to use other means to get credentials.

**Comment by ebourg** [comment]
The implementation has been merged with a few changes. The new `AmazonCredentials` class centralizes the access to the credentials and hides the fetching logic, It supports the EC2 instance credentials and credentials set in the environment variables. It could be extended to also load the credentials from a local `~/.aws/credentials` file as used by the AWS CLI.

Could you test and confirm I haven't broken anything?

**Comment by vmal-altium** [comment]
Sorry for the delay.
I have just tested the 5.0 release, and it's all fine for the AWS credentials from IMDS, as well as detecting mismatches between private/public keys.
Thanks a lot for the mention in the release notes.

**Comment by ebourg** [comment]
Thanks again for the help!

**Comment by ebourg** [comment]
@sbstjn The 169.254.170.2 host is another IMDS service or something different? Do you know if there is an environment variable that could be used to detect that it's running in ECS with Fargate?

**Comment by sbstjn** [comment]
Fargate can be weird and is doing stuff in it's own ways sometimes. 

ECS based on EC2
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ec2-metadata.html

ECS with Fargate
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-metadata.html

I did not dig deeper than that; just happy with what I figured :D 

> The environment variable is AWS_EXECUTION_ENV. Its value is AWS_ECS_EC2 for EC2 and AWS_ECS_FARGATE for Fargate. This is available with fargate platform >= 1.3.0 ( https://stackoverflow.com/a/56049606 )

**Comment by ebourg** [comment]
@sbstjn Is the variable `AWS_CONTAINER_CREDENTIALS_FULL_URI` set in your Fargate environment? I wonder if this could be used instead of guessing the host returning the credentials (i.e. 169.254.169.254 for EC2 and 169.254.170.2 for Fargate)

**Comment by ebourg** [comment]
@idleawhile Thank you fo the input!

> @ebourg Would it be possible to implement the key extraction from relative url in jsign for AWS Containers?

Yes, but I'll need some help to test it.

Could you check if the `AWS_CONTAINER_CREDENTIALS_FULL_URI` variable is set in your AWS Codebuild environment?

**Comment by idleawhile** [comment]
> @idleawhile Thank you fo the input!
> 
> > @ebourg Would it be possible to implement the key extraction from relative url in jsign for AWS Containers?
> 
> Yes, but I'll need some help to test it.
> 
> Could you check if the `AWS_CONTAINER_CREDENTIALS_FULL_URI` variable is set in your AWS Codebuild environment?
Full Url is not part of, the url needs to be built of the default host + AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
Example subset of env vars:
```
AWS_EXECUTION_ENV=AWS_ECS_EC2
AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=/v2/credentials/***
AWS_DEFAULT_REGION=eu-central-1
AWS_REGION=eu-central-1
CODEBUILD_BUILD_IMAGE=aws/codebuild/amazonlinux2-x86_64-standard:5.0
ECS_CONTAINER_METADATA_URI_V4=http://169.254.170.2/v4/***
ECS_AGENT_URI=http://169.254.170.2/api/***
ECS_CONTAINER_METADATA_URI=http://169.254.170.2/v3/***
```

**Comment by vmal-altium** [comment]
Possibly not relevant for Fargate, but when working within containers on EC2, you need to increase the IMDS hop limit to 2 for it to work ([Instance metadata access considerations](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html#imds-considerations))

**Comment by ebourg** [comment]
For the reference, the container credentials provider implementation in the AWS SDK:
https://github.com/aws/aws-sdk-java-v2/blob/2.27.17/core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ContainerCredentialsProvider.java

It looks for `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` first and then falls back to `AWS_CONTAINER_CREDENTIALS_FULL_URI`. `AWS_CONTAINER_AUTHORIZATION_TOKEN` and `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE` are also taken into account.
