### ISSUE TITLE
Support BouncyCastle 1.53

### ISSUE THREAD

**Issue by mlundblad** [ebourg/jsign#18]
Hi there!

In the SignServer project we are using jsign to support Authenticode code signing.
We are now in the process of porting our software to newer versions of BouncyCastle.
I have a local build of jsign built with BC 1.53.

**Comment by mlundblad** [comment]
Patch for building with BC 1.53
[bc153.txt](https://github.com/ebourg/jsign/files/48263/bc153.txt)

**Comment by mlundblad** [comment]
Removed some cruft in earlier patch.
[bc153.txt](https://github.com/ebourg/jsign/files/48265/bc153.txt)

**Comment by ebourg** [comment]
Hi Marcus, thank you very much for the patch, I'll merge it.

**Comment by nedtwigg** [comment]
FWIW, all tests still pass with the patch.  Bumping to 1.54 compiles but most of the tests fail.

**Comment by netmackan** [comment]
Should be okay to merge this patch then if I understood correctly but we might have to create a new one later for 1.54+.
