### ISSUE TITLE
--replace option not working for msix installer

### ISSUE THREAD

**Issue by jasonvooo** [ebourg/jsign#196]
Thanks for releasing 6.0 with msix installer!

I am running into an issue with using the `--replace` option when using jsign to sign a `msix` package. I am under the impression that when using this flag it should replace the existing signature and replace it with the new signature however when running it results in an artefact that has no signature present.

**Comment by jasonvooo** [comment]
When exporting as a zip I see the `AppxSignature.p7x` file but when opening the file through explorer properties you cannot see the digital signature.

Before and after running jsign with `--replace`
![image](https://github.com/ebourg/jsign/assets/14245160/b1fd9a7d-1d65-4b4a-a52b-aae281653b11)

![image](https://github.com/ebourg/jsign/assets/14245160/2d23496e-0bbf-442d-b0d9-e8426ea5c776)

**Comment by ebourg** [comment]
Could you send the two files, before and after replacing the signature, to ebourg@apache.org please? I'd like to inspect them.

**Comment by ebourg** [comment]
@jasonvooo I think this is now fixed, please let me know how it works for you.
