### ISSUE TITLE
.bin & .rom File Support

### ISSUE THREAD

**Issue by isagargit** [ebourg/jsign#241]
I am looking at jsign as a alternative to signtool. Rest all file types are good wanted to know if .bin & .rom (part of BIOS files) are planned to be supported by jSign ?

**Comment by ebourg** [comment]
Do you have an example of .bin or .rom file? If they are PE based like EFI bios they should already be supported by Jsign.

**Comment by isagargit** [comment]
Hey @ebourg, sorry for paused updates here. I was able to sign bin files. They were indeed PE based. So could sign them. 

This issue can be marked closed.
