### ISSUE TITLE
Allowing pipes in passwords [windows]

### ISSUE THREAD

**Issue by pustekuchen91** [ebourg/jsign#255]
Hello folks,

it seems that `|` in passwords leads to an error message when calling jsign under windows. I had no problems calling this on a unix client.

Error Message 
`Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.`
`The filename, directory name, or volume label syntax is incorrect`

`jsign --keystore csaas.cfg --alias myalias --storepass $env:STORE_PASS -storetype PKCS11 --tsaurl http://timestamp.entrust.net/rfc3161ts2 --tsmode RFC3161 MyApplication.exe`

if i remove the `|` from the password i got the response that the login failed.

**Comment by ebourg** [comment]
Does it work better if you remove the dollar sign before `env:`?

**Comment by pustekuchen91** [comment]
> Does it work better if you remove the dollar sign before `env:`?

this makes no difference. It also dont work if the password is provided directly without using any variables

`jsign --keystore csaas.cfg --alias myalias --storepass "MyPasswordWithA|" -storetype PKCS11 --tsaurl http://timestamp.entrust.net/rfc3161ts2 --tsmode RFC3161 MyApplication.exe`

**Comment by pustekuchen91** [comment]
Hello @ebourg,

im using powershell, so the escape character is a backtick ```. But even when i'm escaping the pipe in the password, it outputs the same error.

`jsign --keystore csaas.cfg --alias myalias --storepass "MyPasswordWithA`|" -storetype PKCS11 --tsaurl http://timestamp.entrust.net/rfc3161ts2 --tsmode RFC3161 MyApplication.exe`

I've also tried this 
$storePass = "$($env:STORE_PASS -replace '\|', '`|')"

`jsign --keystore csaas.cfg --alias myalias --storepass $storePass -storetype PKCS11 --tsaurl http://timestamp.entrust.net/rfc3161ts2 --tsmode RFC3161 MyApplication.exe`

but still the same error

**Comment by ebourg** [comment]
I'm not familiar with PowerShell but it seems there are other ways to escape the pipe character, see:
https://octopus.com/blog/powershell-pipe-escaping

Maybe this could work:

    jsign --keystore csaas.cfg --alias myalias --storepass '"MyPasswordWithA|"' -storetype PKCS11 --tsaurl http://timestamp.entrust.net/rfc3161ts2 --tsmode RFC3161 MyApplication.exe

**Comment by pustekuchen91** [comment]
it works locally with 
```
jsign --keystore csaas.cfg --alias myalias --storepass "`"$storePass`"" -storetype PKCS11 --tsaurl http://timestamp.entrust.net/rfc3161ts2 --tsmode RFC3161 MyApplication.exe
```

Maybe someone else could take use of this.

But i'm trying to use the call ina gitlab ci/cd pipeline, which wont work. did serveral combinations.

**Comment by ebourg** [comment]
If you can't sort out the escaping you can use the `env:` (no `$`) of `file:` prefixes to read the password from the environment variables or from a file, bypassing the shell pitfalls:

```
jsign --keystore csaas.cfg --alias myalias --storepass env:STOREPASS -storetype PKCS11 --tsaurl http://timestamp.entrust.net/rfc3161ts2 --tsmode RFC3161 MyApplication.exe
```

```
jsign --keystore csaas.cfg --alias myalias --storepass file:storepass.txt -storetype PKCS11 --tsaurl http://timestamp.entrust.net/rfc3161ts2 --tsmode RFC3161 MyApplication.exe
```

**Comment by pustekuchen91** [comment]
> it works locally with
> 
> ```
> jsign --keystore csaas.cfg --alias myalias --storepass "`"$storePass`"" -storetype PKCS11 --tsaurl http://timestamp.entrust.net/rfc3161ts2 --tsmode RFC3161 MyApplication.exe
> ```
> 
> Maybe someone else could take use of this.
> 
> But i'm trying to use the call ina gitlab ci/cd pipeline, which wont work. did serveral combinations.

I have managed to get it to work with this variant in the pipeline. There was another mistake that I overlooked. The `file` variant also works.

Thank you for helping out :)
