### ISSUE TITLE
Error when signing msi file

### ISSUE THREAD

**Issue by scottmwalton** [ebourg/jsign#257]
When I attempt to sign an msi file, I get the following error message:

C:\> jsign --storetype YUBIKEY --storepass <6 digits here> '.\MyMsiFile.msi'
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Adding Authenticode signature to .\MyMsiFile.msi
C:\>

While it appears to have completed anyway, the file is unchanged.  When I sign exe files or power shell scripts, the app works fine.  It just happens with msi files. I have tried with multiple msi files from different projects that I have developed, and all have the same result. Please let me know if you need additional information.

UPDATE:
After more digging on the web, I changed the parameters that I sent to jsign and it still produces the error message, however now it does sign the msi file. See the updated command line below

C:\> jsign --storetype YUBIKEY --storepass <6 digits here> --certfile full-chain.pem '.\MyMsiFile.msi'

**Comment by ebourg** [comment]
Hi Scott, you can safely ignore this error, it's just a warning message due to a misconfigured logger. It has been fixed in the upcoming version 7.0 (#148).
