### ISSUE TITLE
Sign any file

### ISSUE THREAD

**Issue by phucly01** [ebourg/jsign#265]
I am new to jsign.  I tried to sign a linux file and the error states that the file isn't supported.  It seems like jsign can sign only a handful of files with specific extensions.  This is very limited for its capability.  
Can we add a default to sign any file as binary with or without extension so that it works better in Linux?

**Comment by ebourg** [comment]
For now Jsign is focused on Authenticode signing, its scope may be widened to other types of signatures in the future (JAR, APK, PDF, macOS binaries) but signing any file seems a bit far fetched. Why would you prefer using Jsign instead of existing tools such as GPG?

**Comment by phucly01** [comment]
Because Jsign is one of the tools used by DigiCertONE for PKCS11 other than JarSigner.  JarSigner can't sign large file.    I took a look around in the code and it seems like the core classes were design for specific file format.  I am guessing that in order to support any file the architecture needs to be changed.  What would it take to support any file signing?

**Comment by phucly01** [comment]
I want to sign a linux executable file.  The executable can be a script, binary executable, or combination of the two.  The signature is SHA256withRSA and the private key is a 3K RSA, if it makes any different.

> JarSigner is the signing tool for JAR files, I'm not aware of a file size limit though.

That is why I tried to use jsign.  Some people have issues with the file size.

**Comment by ebourg** [comment]
> I want to sign a linux executable file. The executable can be a script, binary executable, or combination of the two. The signature is SHA256withRSA and the private key is a 3K RSA, if it makes any different.

The right tool for that would be GPG.

**Comment by ebourg** [comment]
It doesn't look like there is a canonical way to sign ELF executables, there were experiments like [signelf](https://sourceforge.net/projects/signelf/) and [DigSig](https://disec.sourceforge.net) but none really took off.

Also worth reading:
https://stackoverflow.com/questions/1732927/signed-executables-under-linux

This issue isn't really actionnable unfortunately, if you need a specific file format to be supported by Jsign I need more information like a signed file example, a specification or a reference implementation.

**Comment by mbrevda** [comment]
+1 for pdf signing. It seems that a lot of the infrastructure is already in place for this project, and it would be great if it could be adopted for pdfs. Thanks!
