### ISSUE TITLE
Support Bouncy Castle 1.54

### ISSUE THREAD

**Issue by netmackan** [ebourg/jsign#30]
Parsing of signature in Jsign is broken with Bouncy Castle 1.54 due to the introduced more strict checking of the ASN.1 objects read from the input. In the new version it is not allowed to have extra data after the object read. This happens with the extra padding that might be added by Jsign to pad to an 8 byte boundary.

The comment here suggests this issue is known:
https://github.com/ebourg/jsign/blob/bcfcad1218100a3758a82687374b24f28b8dbfd0/src/main/java/net/jsign/pe/CertificateTableEntry.java#L77

It was also mentioned in #18.

We can potentially get around this new restriction in BC by creating ContentInfo object ourselves.

**Comment by ebourg** [comment]
Is it any better with BouncyCastle 1.56? I haven't tried yet.

**Comment by netmackan** [comment]
I haven't tried 1.56 yet. We can not go higher than 1.54 at the moment due to other dependencies.
With the pull request I am about to submit, Jsign will work with both 1.53 and 1.54 (at least).

**Comment by ebourg** [comment]
Thank you for the fix Markus. I bumped the version of BC to 1.54.
