### ISSUE TITLE
When using jsign its saying "No Signature present in the subject when viewing Digital Signature details."

### ISSUE THREAD

**Issue by dmodoomsirius** [ebourg/jsign#35]
![chrome_2017-03-10_01-25-01-a3f576fb-037a-4cf1-bf08-a653b2df514e](https://cloud.githubusercontent.com/assets/4022743/23784517/7a440b18-0530-11e7-8e55-8ebc1c967200.png)

This is what i am seeing.

I get this when using the new gradle plugin and through command line.

**Comment by ebourg** [comment]
Hi, were both SHA1 and SHA256 signatures created by jsign? Is the SHA256 signature viewed as valid in this case?

**Comment by dmodoomsirius** [comment]
no both show the same thing.

**Comment by dmodoomsirius** [comment]
noticed I didn't have a p12 file. now i need to realize how to reference it with the cert file like signtool does with /f

```
/f <file>   Specify the signing cert in a file. If this file is a PFX with
            a password, the password may be supplied with the "/p" option.
            If the file does not contain private keys, use the "/csp" and "/kc"
            options to specify the CSP and container name of the private key.
```

Once i figure out that.

when i tested with sign tool using 
```
"C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe" sign /debug /a /p "pass" /csp "CodeSign.p12" /k "CodeSign.p12" "ExeTosign"
```

**Comment by dmodoomsirius** [comment]
Seems to be fixed. was a issue on my end.

**Comment by clarkmcc** [comment]
@dmodoomsirius how did you resolve this issue when using jsign?
