### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by mlocati** [ebourg/jsign#36]
Currently, the [latest release](https://github.com/ebourg/jsign/releases) is 1.3.
A [lot of work](https://github.com/ebourg/jsign/compare/1.3...master) has been done since then: is it time for a new release?

**Comment by ebourg** [comment]
Hi Michele, yes I plan to publish the new release soon. I was waiting for more feedback on the new features first, and it seems multiple signatures aren't working perfectly yet (see #35). Once this is resolved I'll push the new release.

**Comment by mlocati** [comment]
Thanks for the quick response, Emmanuel!

I wanted to try the latest version, but I can't find any instruction about how to create the jsign CLI, neither on https://ebourg.github.io/jsign/ not in the repository.

Here's what I managed to do so far (I'm on a clean Ubuntu 16.04):

```sh
sudo apt update && sudo apt install -y openjdk-8-jdk maven git
cd && git clone https://github.com/ebourg/jsign.git
cd ~/jsign
mvn compile
```

...and now?

**Comment by ebourg** [comment]
You just have to run `mvn package`, the .deb file can then be found in the `jsign/target` directory.

**Comment by mlocati** [comment]
2.0 is here :wink:

**Comment by ebourg** [comment]
Almost :) I still have to upload it to Maven Central.
