### ISSUE TITLE
Update version number from 1.2

### ISSUE THREAD

**Issue by mlocati** [ebourg/jsign#37]
I think that we need to have 1.3 (or 1.4 for the upcoming release) instead of 1.2 here:

- https://github.com/ebourg/jsign/blob/89c6de38270487f3d67d768f1bf0eb71bc520f4/jsign/src/deb/data/usr/share/jsign/pesign.sh#L3
- https://github.com/ebourg/jsign/blob/89c6de38270487f3d67d768f1bf0eb71bc520f4/jsign/src/deb/data/usr/share/man/man1/pesign.1#L2

**Comment by ebourg** [comment]
Good point, thank you for spotting this. These version numbers should be replaced automatically during the build.
