### ISSUE TITLE
Please release to Gradle Plugin Portal

### ISSUE THREAD

**Issue by Vampire** [ebourg/jsign#45]
It would be nice if you would release the Gradle plugin to the Gradle Plugin Portal and also support the new plugin DSL.
This way it would be much easier to use your plugin, as all you need would be

```groovy
plugins {
    id 'net.jsign' version '2.0'
}
```

without any further repositories or dependencies configuration.

**Comment by ebourg** [comment]
Besides publishing to the Gradle Plugin Portal is there anything that should be done to support the new DSL?

**Comment by Vampire** [comment]
Actually yes, you need a separate plugin marker artifact.

There are two aspects.

Maven Central (or any other repository) vs. Gradle Plugin Portal
-----------------------------------------------------------------
In `settings.gradle` you can use
```groovy
pluginManagement {
    repositories {
        mavenCentral()
    }
}
```
To use Maven Central instead of the plugin portal or 
```groovy
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}
```
to use both for resolving plugins from the new plugins DSL.

In that regard the Gradle Plugin Portal is just a different repository and the default that is used if nothing is configured is the plugin portal which makes it easier to use of course if the plugin is released there.

Old style plugin applying vs. new plugins DSL
----------------------------------------------
With the old style you add the artifact by explicit coordinates to the buildscript classpath and then apply the plugin by ID.

With the new plugins DSL the only information available is the globally unique ID for the plugin. The logic to find the respective artifact to add to the buildscript classpath is, that in the `pluginManagement` repositories an artifact at the coordinates `<plugin.id>:<plugin.id>.gradle.plugin:<plugin.version>` is searched, this is the so-called "[Plugin Marker Artifact](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers)" and then has to have a dependency on the actual plugin artifact that is to be added to the buildscript classpath.

---

If you would use Gradle and the `java-gradle-plugin` Gradle plugin, the marker artifact, the plugin descriptor generation for META-INF and so on would all be handled automatically by the plugin. If you want to continue to use Maven for your complete build, after looking at that plugins source quickly I think you need to additionally create the plugin marker artifact within your build and publish both artifacts to repository `https://plugins.gradle.org/m2` which is the Gradle plugin portal address after getting access as described at https://plugins.gradle.org/docs/submit.

**Comment by Vampire** [comment]
I know it is quite some text, but if you read it until the end, you have the answer. ;-)
Actually i never tried it, but I'd guess yes as the Gradle plugins doest not do much more.

**Comment by Vampire** [comment]
Actually the new plugins DSL can already be used right now if you compensate for missing plugin marker artifact and publishing to plugin portal by including the following to `settings.gradle`, just in case someone is interested:

```groovy
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    resolutionStrategy {
        eachPlugin {
            switch (requested.id.id) {
                case 'net.jsign':
                    useModule "net.jsign:jsign-gradle-plugin:$requested.version"
                    break
            }
        }
    }
}
```

**Comment by ebourg** [comment]
I'm not sure to see how plugins are published to https://plugins.gradle.org/m2 using the API keys though.

**Comment by Vampire** [comment]
I guess the publish key is to be used as username and the publish secret as password, but I don't know exactly. I'm probably blind but I didn't find that part in the plugin and as I said, never released one without using Gradle.

**Comment by Vampire** [comment]
Ah, no, I had another look and looked at the wrong plugin.
The `plugin-publish` plugin that does the actual uploading to plugin portal is closed-source.
I've had a quick look and it seems it speaks some OAuth REST API with the plugin portal.
I don't know whether they also provide some Maven plugin to do it.
Maybe it would be easiest to at least do the publishing with Gradle.
Maybe there is something, but a quick Google search didn't help.
Maybe you can use the Gradle plugin in the Maven build somehow.
Maybe you might want to ask at http://discuss.gradle.org/.

**Comment by Vampire** [comment]
If there is no Maven plugin or similar, https://github.com/LendingClub/gradle-maven-plugin might help you

**Comment by ebourg** [comment]
The plugin has been submitted and is pending approval

**Comment by ebourg** [comment]
The plugin has been approved: https://plugins.gradle.org/plugin/net.jsign
