### ISSUE TITLE
Version 2.1 Status

### ISSUE THREAD

**Issue by samuel-mino** [ebourg/jsign#47]
Is there a release date for version 2.1? I am particularly interested in the SunPKCS11 config file loading from any directory feature.

Thanks!

**Comment by dominicE** [comment]
Same here

**Comment by ebourg** [comment]
I'll try to cut the release in September.

**Comment by ebourg** [comment]
Jsign 2.1 is out. The artifacts should appear on Maven Central soon. Thanks all for your help and support.
