### ISSUE TITLE
Support MSI's

### ISSUE THREAD

**Issue by ehershey** [ebourg/jsign#5]
This would be great!

**Comment by addicticks-dev** [comment]
FYI.

You can look into [OpenSSLSignCode tool](http://osslsigncode.sourceforge.net/) which is open source pure-C and platform independent, meaning that it is all just plain-vanilla C code, no cheating by calling Win32 APIs.This library supports MSI files and CAB files. There's only one C source file and the difference  - when signing - between PE files, MSI files and CAB files seems to be rather small. So I guess it should be possible.

**Comment by ebourg** [comment]
Thank you for the reference!

**Comment by ebourg** [comment]
MSI signing is now implemented. Please give it a try and let me know how it works for you.
