### ISSUE TITLE
Maven plugin does not use maven proxy settings

### ISSUE THREAD

**Issue by ebayedq** [ebourg/jsign#51]
The Maven plugin does not use maven proxy settings defined ~/.m2/settings.xml when it calls the timestamping service. Unfortunately, you also can't switch off the timestamping step because the `tsmode` property has a default value, so `PESignerHelper` always ends up enabling it:

`new PESigner(chain, privateKey).withTimestamping(tsaurl != null || tsmode != null)...`

Altogether this means that you can't use the plugin at all, if you're behind a proxy.

**Comment by ebourg** [comment]
Thank you for the feedback, I'll look into that.

**Comment by ebayedq** [comment]
I just found this project which has solved the issue pragmatically, it seems: https://github.com/webdriverextensions/webdriverextensions-maven-plugin.

The relevant code is in [ProxyUtils.java](https://github.com/ebayedq/webdriverextensions-maven-plugin/blob/master/src/main/java/com/github/webdriverextensions/ProxyUtils.java).

**Comment by ebourg** [comment]
Nice, do you want to try to provide a fix based on this implementation (minus the use of the httpclient if possible) ?

**Comment by ebayedq** [comment]
Sure, I'll have a go at it!

**Comment by ebayedq** [comment]
Since jsign-core already supports proxies, I think this is all that's needed: https://github.com/ebayedq/jsign/commit/bab4d1d6bb12ffdf37414e6158f283a71258b4a1

I will try it out tomorrow at the office with my company's proxy.

**Comment by ebourg** [comment]
It looks good, let me know how it works with your proxy, I don't have one to test it.

I've also disabled the timestamping by default in the plugin (fd9b4d4d8864)

**Comment by ebayedq** [comment]
I tested https://github.com/ebourg/jsign/pull/52 with a real proxy today and it works great.
