### ISSUE TITLE
Support Maven encrypted passwords

### ISSUE THREAD

**Issue by Paris** [ebourg/jsign#62]
Using a plaintext password for `keypass` and `storepass` is undesirable when the `pom.xml` is included in a repository with other developers.

Maven supports [encrypted passwords](https://maven.apache.org/guides/mini/guide-encryption.html) which is used in the [jarsigner](https://maven.apache.org/plugins/maven-jarsigner-plugin/usage.html) plugin.

**Comment by Paris** [comment]
I didn't see this was already requested (#53).

**Comment by ebourg** [comment]
I take this as a request to actually cut the release :)
