### ISSUE TITLE
jsign-maven-plugin with empty password keystore 

### ISSUE THREAD

**Issue by iibm1** [ebourg/jsign#63]
i have a keystore with empty password.
using command line : 

    java -jar jsign-2.1.jar --keystore mykeystore.pfx --storepass '' --storetype PKCS12 -a 1 myexe.exe

works perfectly !

trying to do the same with maven plugin do not work

      <plugin>
        <groupId>net.jsign</groupId>
        <artifactId>jsign-maven-plugin</artifactId>
        <version>2.1</version>
        <executions>
          <execution>
            <goals>
              <goal>sign</goal>
            </goals>
            <phase>verify</phase>
            <configuration>
              <file>target/myexe.exe</file>
              <keystore>src/main/resources/cert/mykeystore.pfx</keystore>
              <alias>1</alias>
              <storepass></storepass>
              <storetype>PKCS12</storetype>
            </configuration>
          </execution>
        </executions>
      </plugin>

and get error : 

    No certificate found under the alias '1' in the keystore mykeystore.pfx

Problem come from the fact that maven consider 

    <storepass></storepass> as <storepass/> and means storepass=null

**Comment by ebourg** [comment]
Could you try something like this:

    <storepass><![CDATA[]]></storepass>

**Comment by ebourg** [comment]
Spoiler: just tested and it doesn't work.

**Comment by ebourg** [comment]
A way to work around this issue is to use the Jsign Ant task with the `maven-antrun-plugin` instead of `jsign-maven-plugin`.

**Comment by line-o** [comment]
It's worth trying with
```
<storepass>""</storepass>
```
as this worked with maven-jarsigner-plugin
