### ISSUE TITLE
Support for signing PowerShell scripts

### ISSUE THREAD

**Issue by Vampire** [ebourg/jsign#64]
You can sign PowerShell scripts by adding a signature block with the Authenticode signature.
It would be super nice if JSign would be able to do this too, so we can cross-platform sign our PowerShell scripts.

**Comment by ebourg** [comment]
Thank you for the suggestion. I don't do much PowerShell scripting so I'm unlikely to work on this, but I'm willing to review and merge contributions implementing this.
