### ISSUE TITLE
Sign multiple files as a single execution in maven plugin

### ISSUE THREAD

**Issue by kuntalakrishna** [ebourg/jsign#68]
Came across a requirement which needs me to sign multiple files using jsign-maven-plugin. Currently I can achieve this by repeating <execution> element multiple times. However, there is lot of configuration which repeats for all the files. Instead of <file> xml element can we modify maven mojo to take <files><file>file1</file><file>file2</file></files>?

**Comment by ebourg** [comment]
I agree that would be a nice addition, and if someone implements it I'll be happy to review and merge it.

**Comment by ebourg** [comment]
In the mean time, a shorter alternative is to use the Jsign Ant task with the `maven-antrun-plugin` instead of multiple executions of the `jsign-maven-plugin`.

**Comment by ebayedq** [comment]
If you want to use the Maven plugin, this is still pretty verbose but eliminates the redundancy:

```xml
<plugin>
	<groupId>net.jsign</groupId>
	<artifactId>jsign-maven-plugin</artifactId>
	<version>3.0</version>
	<configuration>
		<keystore>keystore.jks</keystore>
                <alias>test</alias>
                <storepass>password</storepass>
	</configuration>
	<executions>
		<execution>
			<id>file1</id>
			<goals>
				<goal>sign</goal>
			</goals>
			<configuration>
				<file>file1</file>
			</configuration>
		</execution>
		<execution>
			<id>file2</id>
			<goals>
				<goal>sign</goal>
			</goals>
			<configuration>
				<file>file2</file>
			</configuration>
		</execution>
	</executions>
</plugin>
```

**Comment by dyorgio** [comment]
@ebayedq I did this way too. But for large number of files will be nice to have wildcard support.
Like : 
```xml
<wildcard>*.exe</wildcard>
```
or even better:
```xml
<wildcard>*.exe, *.dll</wildcard>
```
or maybe an option like:
```xml
<dir>path of directore where all supported file found are signed</dir>
```
