### ISSUE TITLE
jsign-gradle-plugin kotlin example

### ISSUE THREAD

**Issue by vewert** [ebourg/jsign#72]
Hi,

I am trying to use jsign-gradle-plugin. The gradle example given looks like it uses the groovy syntax. My build file uses Kotlin syntax and I am having trouble getting it to work.

In my build script dependencies I have:

```
dependencies {
    classpath(group = "net.jsign", name = "jsign-gradle-plugin", version = "3.0")
}
```

Then I use:
`apply(plugin = "net.jsign")`

I then try to access jsign with a task (as in the example), but it seems unrecognized and I can't figure out how to include the parameters:

```
task("sign") {
  doLast {
    jsign()
  }
}
```
I'm not sure what I am doing wrong

**Comment by ebourg** [comment]
Sorry I won't be able to help as I'm not using Gradle, but if you figure this out I'd be interested in adding an example to the documentation.

**Comment by ctadlock** [comment]
Any update on this? I can not get it to work with Kotlin Gradle.

```
plugins {
    // kotlin
    kotlin("jvm") version "1.6.10"

    id("net.jsign") version "4.1"
}

repositories {
    mavenCentral()
}
```

Gradle error:
`Plugin [id: 'net.jsign', version: '4.1'] was not found in any of the following sources:`

https://github.com/ebourg/jsign/issues/33

**Comment by ebourg** [comment]
@ctadlock Did you try translating the example in the source code to the Kotlin syntax?

https://github.com/ebourg/jsign/blob/master/jsign-gradle-plugin/example.gradle

It worked when I wrote it 5 years ago, but I don't know if it still does since Gradle often breaks the backward compatibility.

**Comment by ctadlock** [comment]
> @ctadlock Did you try translating the example in the source code to the Kotlin syntax?
> 
> https://github.com/ebourg/jsign/blob/master/jsign-gradle-plugin/example.gradle
> 
> It worked when I wrote it 5 years ago, but I don't know if it still does since Gradle often breaks the backward compatibility.

Yes, I have tried several different ways to get this to work and the plgin can never be found.

**Comment by Sage-Kreiter** [comment]
Any new progress on this? I'm having the same issue trying to use `id("net.jsign") version "4.1"` with Kotlin and Gradle.

**Comment by ctadlock** [comment]
Im pretty sure this is the cause.. 

https://github.com/ebourg/jsign/issues/45

**Comment by ebourg** [comment]
The `id("net.jsign")` syntax won't work (see #45), the plugin has to be added to the classpath.

**Comment by ebourg** [comment]
Here is a syntax that works with the Kotlin DSL:

```
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath("net.jsign:jsign-gradle-plugin:4.1")
    }
}

apply(plugin = "net.jsign")

task("sign") {
    doLast {
        val jsign = project.extensions.getByName("jsign") as groovy.lang.Closure<*>;
        jsign.call(mapOf(
            "file"      to "application.exe",
            "name"      to "My Application",
            "url"       to "http://www.example.com",
            "keystore"  to "keystore.p12",
            "alias"     to "test",
            "storepass" to "secret",
            "tsaurl"    to "http://timestamp.sectigo.com"));
    }
}
```

No need to hack the resolutionStrategy, the apply plugin syntax is much more compact.

If anyone knows how to make the jsign invocation look nicer I'm interested.
