### ISSUE TITLE
The msi signing failed

### ISSUE THREAD

**Issue by borjafg** [ebourg/jsign#73]
I tried to sign a msi file but the ant task failed. I did the same with your minimal-msi file and it worked.

The configuration is the same and the msi I tried to sign was generated with "advance installer".

Advance installer -> https://www.advancedinstaller.com/download.html

========================================

Buildfile: build.xml
 [jsign] Adding Authenticode signature to my_msi.msi

BUILD FAILED
Couldn't sign my_msi.msi

Total time: 1 second

**Comment by ebourg** [comment]
Thank you for the report. Could you send a minimal installer built with this tool to ebourg@apache.org please? I'll give it a look.

**Comment by borjafg** [comment]
I tried with a simple msi that contains only one file and it worked.

I don't understand why it fails with the other msi. The msi size is 80Mb.

**Comment by ebourg** [comment]
Do you get a stacktrace when running Ant in debug mode ?

**Comment by borjafg** [comment]
No, but this Monday I'll try to get the stacktrace by debugging the source code of the library. I don't have the ".msi" here to replicate the error.

In a future version of the library, you should add an optional parameter to print the full stacktrace.

**Comment by ebourg** [comment]
I think I've fixed the issue, could you give it a try?

**Comment by borjafg** [comment]
I will try it this Monday. Right now I don't have the ".msi" that gave me the error.

Thanks.

**Comment by borjafg** [comment]
I tried it again. The bug was fixed with your commit.

Can you make a release or send me a compiled version of the library. I tried to generate the jar myself but the signing fails with that jar.

**Comment by ebourg** [comment]
Thank you for confirming. I'll prepare a new release by next week.

**Comment by ebourg** [comment]
@borjafg the new release is out
