### ISSUE TITLE
CKR_PIN_INCORRECT error for PKCS11

### ISSUE THREAD

**Issue by ymschaap** [ebourg/jsign#79]
[removed]

**Comment by ebourg** [comment]
I guess you've figured out how to solve this since you closed it. I'd like to document how to use various hardware tokens with jsign, so if you want to share how you did I'm interested.

**Comment by ymschaap** [comment]
Sure! I made it work, happy to provide details. It more or less uses the files from this [gist](https://gist.github.com/Littlebigdondon/08bab1f3936d185cdd068608689cc444).

My case and solution:

I have an Electron app, and create a MacOS and Windows build.
To resolve the Windows Defender warning for the .exe file build, I bought an EV code signing certificate.

This came as a SafeNet eToken 5100, a hardware USB stick. I also retrieved a password (by email) which is the _storepass_ value.

Setup:
* Setup locally java, openssl 1.1
* Create a ./hardwareToken.cfg text file

Test:
```keytool -list -keystore NONE -storetype PKCS11 -providerclass sun.security.pkcs11.SunPKCS11 -providerArg ./hardwareToken.cfg```

Should return the alias of the cert.

Build & sign:
* `electron-builder` creates the binaries.
* for the windows binary I run post-build hook javascript file (see gist above).

This is my jsign _command_:
```java -jar ./jsign-3.1.jar --keystore ./hardwareToken.cfg --storepass 'xxxxxx' --storetype PKCS11 --tsaurl http://timestamp.globalsign.com/scripts/timestamp.dll --alias 'xxxxxx' ${configuration.path}```

Which is run by Node post-build:
```require("child_process").execSync(command);```


Note: I opened this ticket because I used double quotes, instead of single quotes for the --storepass, and then it fails with CKR_PIN_INCORRECT.

**Comment by ebourg** [comment]
Nice, thank you!

**Comment by PatricNox** [comment]
Sorry for hijacking, but i'm sitting with a similar case as you @ymschaap. 

I found out that my code signing on the built electron exe (installer) doesn't sign  the binaries within it, does your way of signing it also include the contents to be signed or how is that part handled?
