### ISSUE TITLE
Jsign corrupts launch4j bundled jar within exe container

### ISSUE THREAD

**Issue by falkzilm-nuclos** [ebourg/jsign#80]
I have a maven build with following steps:

- build a maven shade jar as uber jar with all dependencies of the project
- maven jarsigner executes to sign builded jar
- launch4j creates windows executable out of this build&signed jar
- jsign should sign this executable

Build works properly, in windows i can see that the executable has a signature added with conforms to my certificat. 

But im unable to execute it anymore i get following error:

![image](https://user-images.githubusercontent.com/56730556/84148745-b431d080-aa5f-11ea-8c3e-3d9d3375b01e.png)

Does somebody has an idea for debugging or hints how to avoid this? 
I saw somebody writing and using sign4j.exe from https://github.com/fbergmann/launch4j/tree/master/sign4j 

Does this the trick, why does jsign supports launcher4j but seems not work then?

BR,
Falk

**Comment by ebourg** [comment]
What version of Java do you use?

**Comment by falkzilm-nuclos** [comment]
I was using java 8 (1.8.0_241)

**Comment by ebourg** [comment]
Interesting, this issue has already been reported (#4) but with Java 6 only. As far as I understand there is something wrong with the way launch4j loads the embedded jar since this error never happens with other executable wrappers such as exe4j.

**Comment by falkzilm-nuclos** [comment]
So reading this thread lead me to the assumption it is launch4j which does bad stuff, is this right? 
Changing to e.g exe4j could solve the issue then?

**Comment by falkzilm-nuclos** [comment]
This really did the trick. 
This is a workaround i clearly could live with, better then compiling some external program to do weird signing stuff.

And you are completely right with your explanation from my point of view.

**Comment by gillg** [comment]
Finaly what is the trick here ? I have the same issue.

Use `java -cp .\jsign-4.0-SNAPSHOT.jar net.jsign.JsignCLI` instead of `java -jar .\jsign-4.0-SNAPSHOT.jar` ?

It seems not really better for me.

**Comment by ebourg** [comment]
The workaround is to specify the main class in the launch4j configuration.

**Comment by gillg** [comment]
Ah ok ! So I have to rethink it, for now the lanch4j build and signing phase are completely decoralated, in different place, different country, made by different teams... 😅 
If in the meantime you find a stable solution or another workaround I take it !

**Comment by ebourg** [comment]
I can't do much on the Jsign side unfortunately, that's really a launch4j flaw. Your best bet is to have the team responsible for building the .exe to change the launch4j configuration (or switch to an alternative such as exe4j).

**Comment by gillg** [comment]
Sorry I was completly missed... I just understood it's the wrapping command which the "exe" lauch with launch4j.
It's not question to embded jsign in the launch4j project...

Sorry ! I understand !
