### ISSUE TITLE
Signing large MSI files fails

### ISSUE THREAD

**Issue by Sasham111** [ebourg/jsign#82]
Hi,
I tried to use Jsign to sign a large MSI file (311MB), it fails with the following Exception:

`[ec2-user@ip-172-31-35-244 original_jsign]$ jsign -s key.jks --storepass 123456 -storetype jks -a EKM ~/ekm-2.0_large.msi
Adding Authenticode signature to /home/ec2-user/ekm-2.0_large.msi
jsign: Couldn't sign /home/ec2-user/ekm-2.0_large.msi
java.lang.RuntimeException: java.io.IOException: Map failed
        at net.jsign.poi.poifs.filesystem.POIFSStream$StreamBlockByteBufferIterator.next(POIFSStream.java:170)
        at net.jsign.poi.poifs.filesystem.POIFSStream$StreamBlockByteBufferIterator.next(POIFSStream.java:142)
        at net.jsign.msi.MSIFile.computeDigest(MSIFile.java:180)
        at net.jsign.msi.MSIFile.createIndirectData(MSIFile.java:199)
        at net.jsign.AuthenticodeSigner.createSignedData(AuthenticodeSigner.java:368)
        at net.jsign.AuthenticodeSigner.sign(AuthenticodeSigner.java:339)
        at net.jsign.SignerHelper.sign(SignerHelper.java:424)
        at net.jsign.JsignCLI.execute(JsignCLI.java:111)
        at net.jsign.JsignCLI.main(JsignCLI.java:40)
Caused by: java.io.IOException: Map failed
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:938)
        at net.jsign.poi.poifs.nio.FileBackedDataSource.read(FileBackedDataSource.java:95)
        at net.jsign.poi.poifs.filesystem.POIFSFileSystem.getBlockAt(POIFSFileSystem.java:427)
        at net.jsign.poi.poifs.filesystem.POIFSStream$StreamBlockByteBufferIterator.next(POIFSStream.java:166)
        ... 8 more
Caused by: java.lang.OutOfMemoryError: Map failed
        at sun.nio.ch.FileChannelImpl.map0(Native Method)
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:935)
        ... 11 more
`

Signing a small file of 4MB completes successfully. Is there any size limitation of MSI files that can be signed? If so, what is it?
Thanks in advance

**Comment by ebourg** [comment]
Thank you for reporting the issue, the command line tool is configured to use up to 128 MB of RAM, and it looks like the POI API used to read the MSI file loads the whole file in memory, so signing a MSI file of 300 MB leads to an OutOfMemoryError unfortunately.

You can work around the issue by removing the `-Xmx` parameter in `/usr/share/jsign/jsign.sh`. You can also run Jsign with:

    java -jar /usr/share/jsign/jsign-3.1.jar -s key.jks --storepass 123456 -storetype jks -a EKM ekm-2.0_large.msi

I'll check if there is a way to use less memory with POI.

**Comment by Sasham111** [comment]
Hi,
Thanks very much for the quick response. I followed your suggestions by removing -Xmx and running, however it did not solve the issue. Perhaps you have any further insight, any other suggestions? Thanks

**Comment by ebourg** [comment]
Did you try running `java -jar` ?

**Comment by Sasham111** [comment]
Yes, I did run with java -jar in the following way
java -jar /usr/share/jsign/jsign-3.1.jar -s key.jks --storepass 123456 -storetype jks --replace  -a EKM ~/ekm-2.1.1804.44816.Windows.x64.msi

These are the contents of jsign.sh file
#!/bin/sh

java -Djava.net.useSystemProxies=true -Dbasename=`basename "$0"` -jar /usr/share/jsign/jsign-3.1.jar "$@"

Thanks again

**Comment by mrjrkingston** [comment]
Hello,

I have also been running into the issues with Out Of Memory issues when attempting signing. I have tried using `java -jar /path/to/jsign.jar` while specifying `-Xmx` and `-Xms` options to no avail. 

I have also tried to remove the limit inside of `jsign.sh` which did not work either. 

Is there a way to grant jsign more RAM to prevent the out of memory issue?

Thanks.

**Comment by ebourg** [comment]
@mrjrkingston What is the size of the MSI file signed?

**Comment by mrjrkingston** [comment]
The file size was over 100MB, from memory, I think it was closer to 250MB.

**Comment by Sasham111** [comment]
@mrjrkingston  @ebourg
I managed to get it working for large files by using two different POIFSFileSystem objects in MSIFile.java - one for reading (with read only permissions, and the other for writing. I haven't QAd my code completely yet, hence did not publish. 

I defined two objects, one for reading only and the other for writing:
private final POIFSFileSystem fsWrite;
private final POIFSFileSystem fsRead;

**Comment by yaegor** [comment]
We've encountered the issue as well. Fails with "OutOfMemoryError: Map failed" under Linux, does not fail under Windows for a ~300Mb .msi file.
I traced this to vm.max_map_count OS setting. In our case `sysctl vm.max_map_count` was 65530. Bumping it like `sysctl -w vm.max_map_count=262144` makes the command succeed for the file.

It turns out, iterating MSI memory-maps each 4k block without freeing, so currently you need vm.max_map_count to be at least 1000 + (size_of_msi/4096).

**Comment by ebourg** [comment]
@yaegor Thank you for investigating this issue, I'll try your fix.

**Comment by ebourg** [comment]
I've tested the patch on Windows 10 and I still get the "Map failed" error with a 32 bit JDK (#74). @Sasham111 suggestion seems to work on Windows, because POIFSFileSystem maps the file in memory only in rw mode. @yaegor do you think you could test it on Linux too?

**Comment by ebourg** [comment]
I've a better solution, if POIFSFileSystem is instanciated with a FileChannel instead of a File it doesn't map it into memory.

@yaegor could you try this instead ?

    public MSIFile(File file) throws IOException {
        this.fs = new POIFSFileSystem(FileChannel.open(file.toPath(), StandardOpenOption.READ, StandardOpenOption.WRITE), true);
    }

**Comment by yaegor** [comment]
Hi @ebourg,
Unfortunately, that does not help in my Ubuntu test setup.
Your line produces "IllegalArgumentException: POIFS opened in read only mode, so writeFilesystem() may not be called. Open the FileSystem in read-write mode first". When readOnly parameter is changed to false, Ubuntu fails in alike manner as before:
```
...
Caused by: java.lang.OutOfMemoryError: Map failed
	at java.base/sun.nio.ch.FileChannelImpl.map0(Native Method)
	at java.base/sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:1013)
	... 11 more
Try `java -jar jsign.jar --help' for more information.
[1.612s][warning][os,thread] Attempt to deallocate stack guard pages failed (0x00007fecf42f0000-0x00007fecf42f4000).
```

**Comment by yaegor** [comment]
I've tried the read/write [separation solution](https://github.com/yaegor/jsign/commit/e5d1c42d265fcffc6e33c18563736c627dca1b43) and it works for me OK for large files under Linux. This solution also seems to fix signing MSI when running under 32 bit JVM under Windows.

**Comment by ebourg** [comment]
Indeed the channel doesn't work, my test case was incomplete. Thank you for checking. Let's use two POIFSFileSystems then.
