### ISSUE TITLE
Dual signing

### ISSUE THREAD

**Issue by crypticspawn** [ebourg/jsign#86]
How do I dual sign an executable using jsign?

**Comment by jc-lab** [comment]
See https://github.com/ebourg/jsign/blob/b9d5441e702973730f7087c6e27e9f131c8e30c9/jsign-core/src/test/java/net/jsign/PESignerTest.java#L263

**Comment by ebourg** [comment]
jsign appends the signatures by default, so if you call it twice, your file will have two signatures.
