### ISSUE TITLE
Unable to install on Ubuntu 20.04 with the .deb file

### ISSUE THREAD

**Issue by vesubramanian** [ebourg/jsign#90]
E: Invalid archive signature
E: Internal error, could not locate member control.tar.{zstlz4gzxzbz2lzma}
E: Could not read meta data from /root/jsign_3.1_all.deb
E: The package lists or status file could not be parsed or opened.

Getting above errors while trying to install the .deb file on Ubuntu

**Comment by ebourg** [comment]
What is the size of the file downloaded?

**Comment by ebourg** [comment]
I'm unable to reproduce this issue, please reopen if you have more information.
