### ISSUE TITLE
Do not include CMSAlgorithmProtection attribute into signature

### ISSUE THREAD

**Issue by yaegor** [ebourg/jsign#97]
Currently, signatures by jsign include "1.2.840.113549.1.9.52"/"algorithm protect" authenticated attribute.
![jsign-algprotect](https://user-images.githubusercontent.com/3315/125475047-aa45ac2c-3c85-4385-8051-999a711fe9b3.png)

The attribute was also mentioned in another issue [comment](https://github.com/ebourg/jsign/issues/69#issuecomment-566289470).

This does not affect Windows signature verification, but does not seem to be a common practice.
Microsoft's signtool and osslsigncode do not add the attribute.
Actually, the attribute is coming from [RFC6211](https://datatracker.ietf.org/doc/html/rfc6211) which does not seem to be applicable to Authenticode.
Authenticode signatures have the digest algorythm encoded in the contentInfo value, so there seems to be no need in additional attribute for that. For details, search for "The DigestInfo structure has two fields" in the [Authenticode 2008 spec](http://download.microsoft.com/download/9/c/5/9c5b2167-8017-4bae-9fde-d599bac8184a/authenticode_pe.docx).

It seems appropriate to remove the attribute to make the signature more standard.

**Comment by ebourg** [comment]
That makes sense, thank you for digging into this. The digest algorithm is already embedded in the SpcIndirectDataContent structure used in the contentInfo field, so the authenticode signatures are not vulnerable to the algorithm substitution attack described in RFC 6211.
